
name: CI-CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
    - name: Build with Maven
      run: mvn -B -DskipTests package -f app/pom.xml
    - name: Docker build & push
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
        echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin
        docker build -t $DOCKERHUB_USERNAME/devops-portfolio:latest -f docker/Dockerfile .
        docker push $DOCKERHUB_USERNAME/devops-portfolio:latest
    - name: Deploy to Kubernetes
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        echo "$KUBECONFIG" | base64 --decode > kubeconfig
        export KUBECONFIG=$PWD/kubeconfig
        kubectl apply -f k8s/
